# Generated by Django 5.2.13 on 2026-04-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0002_alter_arithmetictask_options_alter_basetask_options_and_more'),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('count', 'Count-based'), ('speed', 'Speed-based'), ('quest', 'Quest-completion')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earners', models.ManyToManyField(blank=True, related_name='badges', to='trainees.traineeprofile')),
                ('reward_avatar', models.ForeignKey(blank=True, help_text='Optional avatar unlocked when this badge is earned.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainees.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('reward_xp', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('reward_badge', models.ForeignKey(blank=True, limit_choices_to={'badge_type': 'quest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.badge')),
                ('tasks', models.ManyToManyField(related_name='quests', to='challenges.basetask')),
            ],
        ),
    ]
