# Generated by Django 5.2.13 on 2026-04-17 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('limited', 'Limited'), ('achievement', 'Achievement')], db_index=True, default='common', max_length=20)),
                ('unlock_type', models.CharField(choices=[('purchase', 'Purchase with coins'), ('achievement', 'Achievement unlock'), ('limited_time', 'Limited-time unlock')], default='purchase', max_length=20)),
                ('coin_cost', models.PositiveIntegerField(default=0, help_text='Cost in coins. Only relevant when unlock_type=PURCHASE.')),
                ('available_from', models.DateTimeField(blank=True, help_text='Start of availability window. Only for LIMITED_TIME type.', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='End of availability window. Only for LIMITED_TIME type.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive avatars are hidden from the shop.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_task', models.ForeignKey(blank=True, help_text='Task that must be completed to unlock. Only for ACHIEVEMENT type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_avatar', to='challenges.basetask')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_avatar', models.ForeignKey(blank=True, help_text='The avatar currently displayed for this child.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trainees.avatar')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to='accounts.childprofile')),
            ],
            options={
                'verbose_name': 'Trainee Profile',
                'verbose_name_plural': 'Trainee Profiles',
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(help_text='How long (in seconds) the child took to complete the task.', validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_snapshot', models.CharField(blank=True, default='', help_text='Difficulty level of the task at the time of completion.', max_length=20)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
                ('avatar_unlocked', models.ForeignKey(blank=True, help_text='Avatar unlocked as a result of this completion, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by_completions', to='trainees.avatar')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='challenges.basetask')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='trainees.traineeprofile')),
            ],
            options={
                'verbose_name': 'Task Completion',
                'verbose_name_plural': 'Task Completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AvatarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_via', models.CharField(choices=[('purchase', 'Purchased with coins'), ('achievement', 'Achievement reward'), ('limited_time', 'Limited-time event'), ('admin_grant', 'Granted by admin')], default='purchase', max_length=20)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='trainees.avatar')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_avatars', to='trainees.traineeprofile')),
            ],
            options={
                'verbose_name': 'Avatar Ownership',
                'verbose_name_plural': 'Avatar Ownerships',
                'ordering': ['-acquired_at'],
                'unique_together': {('trainee', 'avatar')},
            },
        ),
    ]
