# Generated by Django 5.2.13 on 2026-04-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arithmetictask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arithmetic Mission', 'verbose_name_plural': 'Arithmetic Missions'},
        ),
        migrations.AlterModelOptions(
            name='basetask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Mission', 'verbose_name_plural': 'Base Missions'},
        ),
        migrations.AlterModelOptions(
            name='countingtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Counting Mission', 'verbose_name_plural': 'Counting Missions'},
        ),
        migrations.AlterModelOptions(
            name='mazetask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maze Navigation', 'verbose_name_plural': 'Maze Navigations'},
        ),
        migrations.AlterModelOptions(
            name='patternchallenge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pattern Puzzle', 'verbose_name_plural': 'Pattern Puzzles'},
        ),
        migrations.AddField(
            model_name='basetask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='accounts.teacherprofile'),
        ),
    ]
